-g2012
-DIROM_HEX="src0_irom.hex"
-DDRAM_HEX="src0_dram.hex"
-DTEST_NAME="src0"
tb_coe.v
sim_soc.v
../rtl/cpu_core.sv
../rtl/stage_if.sv
../rtl/stage_id.sv
../rtl/stage_ex.sv
../rtl/stage_mem.sv
../rtl/stage_wb.sv
../rtl/pipe_ifid.sv
../rtl/pipe_idex.sv
../rtl/pipe_exmem.sv
../rtl/pipe_memwb.sv
../rtl/control_unit.sv
../rtl/imm_gen.sv
../rtl/csr_unit.sv
../rtl/hazard_unit.sv
../rtl/forwarding_unit.sv
../rtl/div_unit.sv
../rtl/issue_unit.sv
