// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vsim_soc__pch.h"
#include "Vsim_soc.h"
#include "Vsim_soc___024root.h"

// FUNCTIONS
Vsim_soc__Syms::~Vsim_soc__Syms()
{
}

Vsim_soc__Syms::Vsim_soc__Syms(VerilatedContext* contextp, const char* namep, Vsim_soc* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
{
        // Check resources
        Verilated::stackCheck(269);
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_sim_soc.configure(this, name(), "sim_soc", "sim_soc", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_sim_soc__u_cpu.configure(this, name(), "sim_soc.u_cpu", "u_cpu", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_sim_soc__u_cpu__u_csr.configure(this, name(), "sim_soc.u_cpu.u_csr", "u_csr", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_sim_soc__u_cpu__u_ex.configure(this, name(), "sim_soc.u_cpu.u_ex", "u_ex", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_sim_soc__u_cpu__u_ex__u_div.configure(this, name(), "sim_soc.u_cpu.u_ex.u_div", "u_div", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_sim_soc__u_cpu__u_fwd.configure(this, name(), "sim_soc.u_cpu.u_fwd", "u_fwd", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_sim_soc__u_cpu__u_hazard.configure(this, name(), "sim_soc.u_cpu.u_hazard", "u_hazard", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_sim_soc__u_cpu__u_if.configure(this, name(), "sim_soc.u_cpu.u_if", "u_if", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_sim_soc__u_cpu__u_mem.configure(this, name(), "sim_soc.u_cpu.u_mem", "u_mem", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_sim_soc__u_cpu__u_pipe_exmem.configure(this, name(), "sim_soc.u_cpu.u_pipe_exmem", "u_pipe_exmem", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_sim_soc__u_cpu__u_pipe_idex.configure(this, name(), "sim_soc.u_cpu.u_pipe_idex", "u_pipe_idex", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_sim_soc__u_cpu__u_pipe_ifid.configure(this, name(), "sim_soc.u_cpu.u_pipe_ifid", "u_pipe_ifid", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_sim_soc__u_cpu__u_pipe_memwb.configure(this, name(), "sim_soc.u_cpu.u_pipe_memwb", "u_pipe_memwb", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_sim_soc__u_cpu__u_stage_id.configure(this, name(), "sim_soc.u_cpu.u_stage_id", "u_stage_id", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.configure(this, name(), "sim_soc.u_cpu.u_stage_id.u_ctrl", "u_ctrl", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_sim_soc__u_cpu__u_stage_id__u_imm_gen.configure(this, name(), "sim_soc.u_cpu.u_stage_id.u_imm_gen", "u_imm_gen", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_TOP.varInsert(__Vfinal,"clk", &(TOP.clk), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"rst_n", &(TOP.rst_n), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"DRAM_BASE", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__DRAM_BASE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"DRAM_END", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__DRAM_END))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"clk", &(TOP.sim_soc__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"cpu_rst", &(TOP.sim_soc__DOT__cpu_rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"dmem", &(TOP.sim_soc__DOT__dmem), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,65535 ,31,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"dram_cur", &(TOP.sim_soc__DOT__dram_cur), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"dram_offset", &(TOP.sim_soc__DOT__dram_offset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"dram_rdata", &(TOP.sim_soc__DOT__dram_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"dram_sel", &(TOP.sim_soc__DOT__dram_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"dram_wdata", &(TOP.sim_soc__DOT__dram_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"dram_word_addr", &(TOP.sim_soc__DOT__dram_word_addr), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"ii", &(TOP.sim_soc__DOT__ii), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"imem", &(TOP.sim_soc__DOT__imem), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,4095 ,31,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"irom_addr", &(TOP.sim_soc__DOT__irom_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"irom_data", &(TOP.sim_soc__DOT__irom_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"perip_addr", &(TOP.sim_soc__DOT__perip_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"perip_mask", &(TOP.sim_soc__DOT__perip_mask), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"perip_rdata", &(TOP.sim_soc__DOT__perip_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"perip_wdata", &(TOP.sim_soc__DOT__perip_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"perip_wen", &(TOP.sim_soc__DOT__perip_wen), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc.varInsert(__Vfinal,"rst_n", &(TOP.sim_soc__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"cpu_clk", &(TOP.sim_soc__DOT__u_cpu__DOT__cpu_clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"cpu_rst", &(TOP.sim_soc__DOT__u_cpu__DOT__cpu_rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"csr_mepc", &(TOP.sim_soc__DOT__u_cpu__DOT__csr_mepc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"csr_mtvec", &(TOP.sim_soc__DOT__u_cpu__DOT__csr_mtvec), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"direction_mismatch", &(TOP.sim_soc__DOT__u_cpu__DOT__direction_mismatch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"div_stall", &(TOP.sim_soc__DOT__u_cpu__DOT__div_stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"ex_alu_result", &(TOP.sim_soc__DOT__u_cpu__DOT__ex_alu_result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"ex_branch_taken", &(TOP.sim_soc__DOT__u_cpu__DOT__ex_branch_taken), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"ex_branch_target", &(TOP.sim_soc__DOT__u_cpu__DOT__ex_branch_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"ex_csr_waddr", &(TOP.sim_soc__DOT__u_cpu__DOT__ex_csr_waddr), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"ex_csr_wdata", &(TOP.sim_soc__DOT__u_cpu__DOT__ex_csr_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"ex_csr_wen", &(TOP.sim_soc__DOT__u_cpu__DOT__ex_csr_wen), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"ex_redirect", &(TOP.sim_soc__DOT__u_cpu__DOT__ex_redirect), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"ex_redirect_target", &(TOP.sim_soc__DOT__u_cpu__DOT__ex_redirect_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"ex_rs2_data_fwd", &(TOP.sim_soc__DOT__u_cpu__DOT__ex_rs2_data_fwd), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"ex_stall", &(TOP.sim_soc__DOT__u_cpu__DOT__ex_stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"ex_trap_epc", &(TOP.sim_soc__DOT__u_cpu__DOT__ex_trap_epc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"ex_trap_mcause", &(TOP.sim_soc__DOT__u_cpu__DOT__ex_trap_mcause), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"ex_trap_valid", &(TOP.sim_soc__DOT__u_cpu__DOT__ex_trap_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"exmem_alu_result", &(TOP.sim_soc__DOT__u_cpu__DOT__exmem_alu_result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"exmem_fwd_data", &(TOP.sim_soc__DOT__u_cpu__DOT__exmem_fwd_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"exmem_mem_funct3", &(TOP.sim_soc__DOT__u_cpu__DOT__exmem_mem_funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"exmem_mem_read", &(TOP.sim_soc__DOT__u_cpu__DOT__exmem_mem_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"exmem_mem_write", &(TOP.sim_soc__DOT__u_cpu__DOT__exmem_mem_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"exmem_pc_plus4", &(TOP.sim_soc__DOT__u_cpu__DOT__exmem_pc_plus4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"exmem_rd_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__exmem_rd_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"exmem_reg_write", &(TOP.sim_soc__DOT__u_cpu__DOT__exmem_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"exmem_rs2_data", &(TOP.sim_soc__DOT__u_cpu__DOT__exmem_rs2_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"exmem_wb_sel", &(TOP.sim_soc__DOT__u_cpu__DOT__exmem_wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"flush", &(TOP.sim_soc__DOT__u_cpu__DOT__flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"forward_a", &(TOP.sim_soc__DOT__u_cpu__DOT__forward_a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"forward_b", &(TOP.sim_soc__DOT__u_cpu__DOT__forward_b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"hz_stall", &(TOP.sim_soc__DOT__u_cpu__DOT__hz_stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_alu_op", &(TOP.sim_soc__DOT__u_cpu__DOT__id_alu_op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_alu_src", &(TOP.sim_soc__DOT__u_cpu__DOT__id_alu_src), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_auipc", &(TOP.sim_soc__DOT__u_cpu__DOT__id_auipc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_branch", &(TOP.sim_soc__DOT__u_cpu__DOT__id_branch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_csr_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__id_csr_addr), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_csr_op", &(TOP.sim_soc__DOT__u_cpu__DOT__id_csr_op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_csr_rdata", &(TOP.sim_soc__DOT__u_cpu__DOT__id_csr_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_csr_rdata_fwd", &(TOP.sim_soc__DOT__u_cpu__DOT__id_csr_rdata_fwd), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_csr_rdata_raw", &(TOP.sim_soc__DOT__u_cpu__DOT__id_csr_rdata_raw), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_ecall", &(TOP.sim_soc__DOT__u_cpu__DOT__id_ecall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_imm", &(TOP.sim_soc__DOT__u_cpu__DOT__id_imm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_jal", &(TOP.sim_soc__DOT__u_cpu__DOT__id_jal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_jalr", &(TOP.sim_soc__DOT__u_cpu__DOT__id_jalr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_mem_funct3", &(TOP.sim_soc__DOT__u_cpu__DOT__id_mem_funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_mem_read", &(TOP.sim_soc__DOT__u_cpu__DOT__id_mem_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_mem_write", &(TOP.sim_soc__DOT__u_cpu__DOT__id_mem_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_mret", &(TOP.sim_soc__DOT__u_cpu__DOT__id_mret), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_rd_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__id_rd_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_reg_write", &(TOP.sim_soc__DOT__u_cpu__DOT__id_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_rs1_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__id_rs1_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_rs1_data", &(TOP.sim_soc__DOT__u_cpu__DOT__id_rs1_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_rs2_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__id_rs2_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_rs2_data", &(TOP.sim_soc__DOT__u_cpu__DOT__id_rs2_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"id_wb_sel", &(TOP.sim_soc__DOT__u_cpu__DOT__id_wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_alu_op", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_alu_op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_alu_src", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_alu_src), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_auipc", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_auipc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_branch", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_branch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_csr_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_csr_addr), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_csr_op", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_csr_op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_csr_rdata", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_csr_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_ecall", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_ecall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_funct3", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_imm", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_imm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_jal", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_jal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_jalr", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_jalr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_mem_funct3", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_mem_funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_mem_read", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_mem_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_mem_write", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_mem_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_mret", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_mret), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_pc", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_pc_plus4", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_pc_plus4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_predicted", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_predicted), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_predicted_target", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_predicted_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_rd_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_rd_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_reg_write", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_rs1_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_rs1_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_rs1_data", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_rs1_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_rs2_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_rs2_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_rs2_data", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_rs2_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"idex_wb_sel", &(TOP.sim_soc__DOT__u_cpu__DOT__idex_wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"if_instruction", &(TOP.sim_soc__DOT__u_cpu__DOT__if_instruction), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"if_pc", &(TOP.sim_soc__DOT__u_cpu__DOT__if_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"if_pc_plus4", &(TOP.sim_soc__DOT__u_cpu__DOT__if_pc_plus4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"if_predicted", &(TOP.sim_soc__DOT__u_cpu__DOT__if_predicted), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"if_predicted_target", &(TOP.sim_soc__DOT__u_cpu__DOT__if_predicted_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"ifid_instruction", &(TOP.sim_soc__DOT__u_cpu__DOT__ifid_instruction), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"ifid_pc", &(TOP.sim_soc__DOT__u_cpu__DOT__ifid_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"ifid_pc_plus4", &(TOP.sim_soc__DOT__u_cpu__DOT__ifid_pc_plus4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"ifid_predicted", &(TOP.sim_soc__DOT__u_cpu__DOT__ifid_predicted), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"ifid_predicted_target", &(TOP.sim_soc__DOT__u_cpu__DOT__ifid_predicted_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"irom_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__irom_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"irom_data", &(TOP.sim_soc__DOT__u_cpu__DOT__irom_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"mem_read_data", &(TOP.sim_soc__DOT__u_cpu__DOT__mem_read_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"memwb_alu_result", &(TOP.sim_soc__DOT__u_cpu__DOT__memwb_alu_result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"memwb_mem_data", &(TOP.sim_soc__DOT__u_cpu__DOT__memwb_mem_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"memwb_pc_plus4", &(TOP.sim_soc__DOT__u_cpu__DOT__memwb_pc_plus4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"memwb_rd_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__memwb_rd_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"memwb_reg_write", &(TOP.sim_soc__DOT__u_cpu__DOT__memwb_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"memwb_wb_sel", &(TOP.sim_soc__DOT__u_cpu__DOT__memwb_wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"memwb_write_data", &(TOP.sim_soc__DOT__u_cpu__DOT__memwb_write_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"mul_stall", &(TOP.sim_soc__DOT__u_cpu__DOT__mul_stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"perip_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__perip_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"perip_mask", &(TOP.sim_soc__DOT__u_cpu__DOT__perip_mask), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"perip_rdata", &(TOP.sim_soc__DOT__u_cpu__DOT__perip_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"perip_wdata", &(TOP.sim_soc__DOT__u_cpu__DOT__perip_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"perip_wen", &(TOP.sim_soc__DOT__u_cpu__DOT__perip_wen), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"pipeline_stall", &(TOP.sim_soc__DOT__u_cpu__DOT__pipeline_stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"target_mismatch", &(TOP.sim_soc__DOT__u_cpu__DOT__target_mismatch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu.varInsert(__Vfinal,"wb_write_data", &(TOP.sim_soc__DOT__u_cpu__DOT__wb_write_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_csr.varInsert(__Vfinal,"clk", &(TOP.sim_soc__DOT__u_cpu__DOT__u_csr__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_csr.varInsert(__Vfinal,"cpu_rst", &(TOP.sim_soc__DOT__u_cpu__DOT__u_csr__DOT__cpu_rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_csr.varInsert(__Vfinal,"csr_raddr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_csr__DOT__csr_raddr), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_sim_soc__u_cpu__u_csr.varInsert(__Vfinal,"csr_rdata", &(TOP.sim_soc__DOT__u_cpu__DOT__u_csr__DOT__csr_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_csr.varInsert(__Vfinal,"csr_waddr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_csr__DOT__csr_waddr), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_sim_soc__u_cpu__u_csr.varInsert(__Vfinal,"csr_wdata", &(TOP.sim_soc__DOT__u_cpu__DOT__u_csr__DOT__csr_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_csr.varInsert(__Vfinal,"csr_wen", &(TOP.sim_soc__DOT__u_cpu__DOT__u_csr__DOT__csr_wen), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_csr.varInsert(__Vfinal,"mcause", &(TOP.sim_soc__DOT__u_cpu__DOT__u_csr__DOT__mcause), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_csr.varInsert(__Vfinal,"mepc", &(TOP.sim_soc__DOT__u_cpu__DOT__u_csr__DOT__mepc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_csr.varInsert(__Vfinal,"mscratch", &(TOP.sim_soc__DOT__u_cpu__DOT__u_csr__DOT__mscratch), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_csr.varInsert(__Vfinal,"mstatus", &(TOP.sim_soc__DOT__u_cpu__DOT__u_csr__DOT__mstatus), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_csr.varInsert(__Vfinal,"mtval", &(TOP.sim_soc__DOT__u_cpu__DOT__u_csr__DOT__mtval), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_csr.varInsert(__Vfinal,"mtvec", &(TOP.sim_soc__DOT__u_cpu__DOT__u_csr__DOT__mtvec), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_csr.varInsert(__Vfinal,"trap_epc", &(TOP.sim_soc__DOT__u_cpu__DOT__u_csr__DOT__trap_epc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_csr.varInsert(__Vfinal,"trap_mcause", &(TOP.sim_soc__DOT__u_cpu__DOT__u_csr__DOT__trap_mcause), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_csr.varInsert(__Vfinal,"trap_valid", &(TOP.sim_soc__DOT__u_cpu__DOT__u_csr__DOT__trap_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"ALU_ADD", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_ADD))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"ALU_AND", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_AND))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"ALU_DIV", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_DIV))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"ALU_DIVU", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_DIVU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"ALU_MUL", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_MUL))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"ALU_MULH", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_MULH))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"ALU_MULHSU", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_MULHSU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"ALU_MULHU", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_MULHU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"ALU_OR", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_OR))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"ALU_PASS_B", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_PASS_B))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"ALU_REM", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_REM))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"ALU_REMU", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_REMU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"ALU_SLL", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_SLL))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"ALU_SLT", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_SLT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"ALU_SLTU", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_SLTU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"ALU_SRA", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_SRA))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"ALU_SRL", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_SRL))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"ALU_SUB", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_SUB))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"ALU_XOR", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_XOR))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"alu_a", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__alu_a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"alu_b", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__alu_b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"alu_out", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__alu_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"alu_result", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__alu_result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"branch_cond", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__branch_cond), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"branch_taken", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__branch_taken), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"branch_target", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__branch_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"clk", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"cpu_rst", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__cpu_rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"csr_mepc", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__csr_mepc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"csr_mtvec", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__csr_mtvec), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"csr_waddr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__csr_waddr), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"csr_wd", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__csr_wd), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"csr_wdata", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__csr_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"csr_wen", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__csr_wen), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"div_busy", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__div_busy), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"div_done", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__div_done), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"div_op_rem", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__div_op_rem), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"div_op_signed", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__div_op_signed), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"div_result", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__div_result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"div_stall", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__div_stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"div_start", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__div_start), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"exmem_fwd_data", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__exmem_fwd_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"forward_a", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__forward_a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"forward_b", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__forward_b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"fwd_a", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__fwd_a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"fwd_b", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__fwd_b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"idex_alu_op", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_alu_op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"idex_alu_src", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_alu_src), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"idex_auipc", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_auipc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"idex_branch", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_branch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"idex_csr_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_csr_addr), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"idex_csr_op", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_csr_op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"idex_csr_rdata", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_csr_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"idex_ecall", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_ecall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"idex_funct3", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"idex_imm", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_imm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"idex_jal", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_jal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"idex_jalr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_jalr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"idex_mret", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_mret), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"idex_pc", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"idex_pc_plus4", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_pc_plus4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"idex_rs1_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_rs1_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"idex_rs1_data", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_rs1_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"idex_rs2_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_rs2_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"idex_rs2_data", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_rs2_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"is_div_op", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__is_div_op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"is_mul_op", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__is_mul_op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"jalr_tgt", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__jalr_tgt), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"mul_a_sign", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__mul_a_sign), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"mul_b_sign", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__mul_b_sign), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"mul_op_a", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__mul_op_a), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,32,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"mul_op_b", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__mul_op_b), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,32,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"mul_result_r", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__mul_result_r), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,65,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"mul_stall", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__mul_stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"mul_valid", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__mul_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"pc_branch", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__pc_branch), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"rs2_data_fwd", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__rs2_data_fwd), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"trap_epc", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__trap_epc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"trap_mcause", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__trap_mcause), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"trap_valid", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__trap_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"wb_write_data", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__wb_write_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex.varInsert(__Vfinal,"zimm", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__zimm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"S_CALC", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__S_CALC))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"S_DONE", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__S_DONE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"S_IDLE", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__S_IDLE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"busy", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__busy), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"can_sub", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__can_sub), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"clk", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"count", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"div_reg", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__div_reg), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"dividend", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__dividend), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"divisor", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__divisor), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"done", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__done), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"is_rem", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__is_rem), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"op_rem", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__op_rem), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"op_signed", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__op_signed), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"q_out", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__q_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"quo", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__quo), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"r_out", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__r_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"rem", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__rem), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"result", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"rst", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"sign_q", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__sign_q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"sign_r", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__sign_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"start", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__start), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"state", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu__u_ex__u_div.varInsert(__Vfinal,"trial", &(TOP.sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__trial), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,32,0);
        __Vscope_sim_soc__u_cpu__u_fwd.varInsert(__Vfinal,"exmem_rd_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_fwd__DOT__exmem_rd_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_fwd.varInsert(__Vfinal,"exmem_reg_write", &(TOP.sim_soc__DOT__u_cpu__DOT__u_fwd__DOT__exmem_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_fwd.varInsert(__Vfinal,"forward_a", &(TOP.sim_soc__DOT__u_cpu__DOT__u_fwd__DOT__forward_a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu__u_fwd.varInsert(__Vfinal,"forward_b", &(TOP.sim_soc__DOT__u_cpu__DOT__u_fwd__DOT__forward_b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu__u_fwd.varInsert(__Vfinal,"idex_rs1_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_fwd__DOT__idex_rs1_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_fwd.varInsert(__Vfinal,"idex_rs2_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_fwd__DOT__idex_rs2_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_fwd.varInsert(__Vfinal,"memwb_rd_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_fwd__DOT__memwb_rd_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_fwd.varInsert(__Vfinal,"memwb_reg_write", &(TOP.sim_soc__DOT__u_cpu__DOT__u_fwd__DOT__memwb_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_hazard.varInsert(__Vfinal,"idex_mem_read", &(TOP.sim_soc__DOT__u_cpu__DOT__u_hazard__DOT__idex_mem_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_hazard.varInsert(__Vfinal,"idex_rd_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_hazard__DOT__idex_rd_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_hazard.varInsert(__Vfinal,"ifid_rs1_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_hazard__DOT__ifid_rs1_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_hazard.varInsert(__Vfinal,"ifid_rs2_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_hazard__DOT__ifid_rs2_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_hazard.varInsert(__Vfinal,"stall", &(TOP.sim_soc__DOT__u_cpu__DOT__u_hazard__DOT__stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"RESET_PC", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__RESET_PC))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"b_imm", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__b_imm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"bht", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__bht), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,511 ,1,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"bht_i", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__bht_i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"bht_predict_taken", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__bht_predict_taken), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"bht_rd_idx", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__bht_rd_idx), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,8,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"bht_update_pc", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__bht_update_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"bht_update_taken", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__bht_update_taken), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"bht_update_valid", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__bht_update_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"bht_wr_current", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__bht_wr_current), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"bht_wr_idx", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__bht_wr_idx), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,8,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"bht_wr_next", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__bht_wr_next), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"branch_predict_taken", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__branch_predict_taken), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"branch_predict_target", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__branch_predict_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"branch_taken", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__branch_taken), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"branch_target", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__branch_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"clk", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"cpu_rst", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__cpu_rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"if_is_branch", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__if_is_branch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"if_is_jal", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__if_is_jal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"if_is_jalr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__if_is_jalr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"if_predict", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__if_predict), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"if_predict_target", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__if_predict_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"if_rd", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__if_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"if_rd_is_link", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__if_rd_is_link), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"if_rs1", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__if_rs1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"if_rs1_is_link", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__if_rs1_is_link), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"instruction", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__instruction), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"irom_data", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__irom_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"irom_word_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__irom_word_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"is_call", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__is_call), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"is_return", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__is_return), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"jal_imm", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__jal_imm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"jal_target", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__jal_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"opcode", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__opcode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"pc_out", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__pc_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"pc_plus4", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__pc_plus4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"predicted", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__predicted), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"predicted_target", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__predicted_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"ras", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__ras), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,7 ,31,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"ras_predict", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__ras_predict), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"ras_ptr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__ras_ptr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"ras_top", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__ras_top), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_if.varInsert(__Vfinal,"stall", &(TOP.sim_soc__DOT__u_cpu__DOT__u_if__DOT__stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_mem.varInsert(__Vfinal,"exmem_alu_result", &(TOP.sim_soc__DOT__u_cpu__DOT__u_mem__DOT__exmem_alu_result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_mem.varInsert(__Vfinal,"exmem_mem_funct3", &(TOP.sim_soc__DOT__u_cpu__DOT__u_mem__DOT__exmem_mem_funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_sim_soc__u_cpu__u_mem.varInsert(__Vfinal,"exmem_mem_read", &(TOP.sim_soc__DOT__u_cpu__DOT__u_mem__DOT__exmem_mem_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_mem.varInsert(__Vfinal,"exmem_mem_write", &(TOP.sim_soc__DOT__u_cpu__DOT__u_mem__DOT__exmem_mem_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_mem.varInsert(__Vfinal,"exmem_rs2_data", &(TOP.sim_soc__DOT__u_cpu__DOT__u_mem__DOT__exmem_rs2_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_mem.varInsert(__Vfinal,"mem_read_data", &(TOP.sim_soc__DOT__u_cpu__DOT__u_mem__DOT__mem_read_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_mem.varInsert(__Vfinal,"perip_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_mem__DOT__perip_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_mem.varInsert(__Vfinal,"perip_mask", &(TOP.sim_soc__DOT__u_cpu__DOT__u_mem__DOT__perip_mask), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu__u_mem.varInsert(__Vfinal,"perip_rdata", &(TOP.sim_soc__DOT__u_cpu__DOT__u_mem__DOT__perip_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_mem.varInsert(__Vfinal,"perip_wdata", &(TOP.sim_soc__DOT__u_cpu__DOT__u_mem__DOT__perip_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_mem.varInsert(__Vfinal,"perip_wen", &(TOP.sim_soc__DOT__u_cpu__DOT__u_mem__DOT__perip_wen), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"clk", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"cpu_rst", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__cpu_rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"ex_alu_result", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__ex_alu_result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"ex_mem_funct3", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__ex_mem_funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"ex_mem_read", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__ex_mem_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"ex_mem_write", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__ex_mem_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"ex_pc_plus4", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__ex_pc_plus4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"ex_rd_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__ex_rd_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"ex_reg_write", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__ex_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"ex_rs2_data", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__ex_rs2_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"ex_wb_sel", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__ex_wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"exmem_alu_result", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__exmem_alu_result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"exmem_fwd_data", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__exmem_fwd_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"exmem_mem_funct3", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__exmem_mem_funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"exmem_mem_read", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__exmem_mem_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"exmem_mem_write", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__exmem_mem_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"exmem_pc_plus4", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__exmem_pc_plus4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"exmem_rd_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__exmem_rd_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"exmem_reg_write", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__exmem_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"exmem_rs2_data", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__exmem_rs2_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"exmem_wb_sel", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__exmem_wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu__u_pipe_exmem.varInsert(__Vfinal,"flush", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"clk", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"cpu_rst", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__cpu_rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"flush", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"hold", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__hold), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_alu_op", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_alu_op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_alu_src", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_alu_src), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_auipc", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_auipc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_branch", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_branch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_csr_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_csr_addr), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_csr_op", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_csr_op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_csr_rdata", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_csr_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_ecall", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_ecall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_funct3", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_imm", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_imm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_jal", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_jal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_jalr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_jalr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_mem_funct3", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_mem_funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_mem_read", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_mem_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_mem_write", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_mem_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_mret", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_mret), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_pc", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_pc_plus4", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_pc_plus4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_predicted", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_predicted), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_predicted_target", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_predicted_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_rd_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_rd_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_reg_write", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_rs1_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_rs1_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_rs1_data", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_rs1_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_rs2_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_rs2_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_rs2_data", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_rs2_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"id_wb_sel", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_alu_op", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_alu_op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_alu_src", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_alu_src), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_auipc", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_auipc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_branch", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_branch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_csr_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_csr_addr), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_csr_op", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_csr_op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_csr_rdata", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_csr_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_ecall", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_ecall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_funct3", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_imm", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_imm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_jal", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_jal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_jalr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_jalr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_mem_funct3", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_mem_funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_mem_read", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_mem_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_mem_write", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_mem_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_mret", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_mret), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_pc", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_pc_plus4", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_pc_plus4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_predicted", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_predicted), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_predicted_target", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_predicted_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_rd_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_rd_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_reg_write", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_rs1_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_rs1_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_rs1_data", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_rs1_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_rs2_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_rs2_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_rs2_data", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_rs2_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_idex.varInsert(__Vfinal,"idex_wb_sel", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu__u_pipe_ifid.varInsert(__Vfinal,"clk", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_ifid.varInsert(__Vfinal,"cpu_rst", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__cpu_rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_ifid.varInsert(__Vfinal,"flush", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_ifid.varInsert(__Vfinal,"if_instruction", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__if_instruction), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_ifid.varInsert(__Vfinal,"if_pc", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__if_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_ifid.varInsert(__Vfinal,"if_pc_plus4", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__if_pc_plus4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_ifid.varInsert(__Vfinal,"if_predicted", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__if_predicted), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_ifid.varInsert(__Vfinal,"if_predicted_target", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__if_predicted_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_ifid.varInsert(__Vfinal,"ifid_instruction", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__ifid_instruction), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_ifid.varInsert(__Vfinal,"ifid_pc", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__ifid_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_ifid.varInsert(__Vfinal,"ifid_pc_plus4", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__ifid_pc_plus4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_ifid.varInsert(__Vfinal,"ifid_predicted", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__ifid_predicted), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_ifid.varInsert(__Vfinal,"ifid_predicted_target", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__ifid_predicted_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_ifid.varInsert(__Vfinal,"stall", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_memwb.varInsert(__Vfinal,"clk", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_memwb.varInsert(__Vfinal,"cpu_rst", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__cpu_rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_memwb.varInsert(__Vfinal,"mem_alu_result", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__mem_alu_result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_memwb.varInsert(__Vfinal,"mem_pc_plus4", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__mem_pc_plus4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_memwb.varInsert(__Vfinal,"mem_rd_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__mem_rd_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_pipe_memwb.varInsert(__Vfinal,"mem_read_data", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__mem_read_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_memwb.varInsert(__Vfinal,"mem_reg_write", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__mem_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_memwb.varInsert(__Vfinal,"mem_wb_sel", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__mem_wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu__u_pipe_memwb.varInsert(__Vfinal,"memwb_alu_result", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__memwb_alu_result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_memwb.varInsert(__Vfinal,"memwb_mem_data", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__memwb_mem_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_memwb.varInsert(__Vfinal,"memwb_pc_plus4", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__memwb_pc_plus4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_pipe_memwb.varInsert(__Vfinal,"memwb_rd_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__memwb_rd_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_pipe_memwb.varInsert(__Vfinal,"memwb_reg_write", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__memwb_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_pipe_memwb.varInsert(__Vfinal,"memwb_wb_sel", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__memwb_wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu__u_pipe_memwb.varInsert(__Vfinal,"memwb_write_data", &(TOP.sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__memwb_write_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"alu_op", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__alu_op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"alu_src", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__alu_src), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"auipc", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__auipc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"branch", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__branch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"clk", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"cpu_rst", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__cpu_rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"csr_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__csr_addr), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"csr_op", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__csr_op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"csr_rdata", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__csr_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"csr_rdata_out", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__csr_rdata_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"ecall", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__ecall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"f3", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__f3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"funct12", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__funct12), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"funct7", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__funct7), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"i", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"imm", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__imm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"instruction", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__instruction), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"jal", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__jal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"jalr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__jalr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"lui", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__lui), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"mem_funct3", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__mem_funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"mem_read", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__mem_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"mem_write", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__mem_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"mret", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__mret), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"opcode", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__opcode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"rd_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__rd_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"reg_write", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"regfile", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__regfile), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1,1 ,1,31 ,31,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"rf_rs1", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__rf_rs1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"rf_rs2", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__rf_rs2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"rs1_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__rs1_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"rs1_data", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__rs1_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"rs2_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__rs2_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"rs2_data", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__rs2_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"wb_rd_addr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__wb_rd_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"wb_reg_write", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__wb_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"wb_sel", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu__u_stage_id.varInsert(__Vfinal,"wb_write_data", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__wb_write_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"ALU_ADD", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_ADD))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"ALU_AND", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_AND))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"ALU_DIV", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_DIV))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"ALU_DIVU", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_DIVU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"ALU_MUL", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_MUL))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"ALU_MULH", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_MULH))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"ALU_MULHSU", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_MULHSU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"ALU_MULHU", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_MULHU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"ALU_OR", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_OR))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"ALU_PASS_B", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_PASS_B))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"ALU_REM", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_REM))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"ALU_REMU", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_REMU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"ALU_SLL", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_SLL))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"ALU_SLT", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_SLT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"ALU_SLTU", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_SLTU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"ALU_SRA", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_SRA))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"ALU_SRL", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_SRL))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"ALU_SUB", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_SUB))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"ALU_XOR", const_cast<void*>(static_cast<const void*>(&(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_XOR))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"alu_op", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__alu_op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"alu_src", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__alu_src), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"auipc", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__auipc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"branch", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__branch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"csr_op", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__csr_op), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"ecall", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ecall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"funct12", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__funct12), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"funct3", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"funct7", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__funct7), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"jal", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__jal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"jalr", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__jalr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"lui", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__lui), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"mem_read", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__mem_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"mem_write", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__mem_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"mret", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__mret), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"opcode", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__opcode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"reg_write", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_ctrl.varInsert(__Vfinal,"wb_sel", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_imm_gen.varInsert(__Vfinal,"imm", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_imm_gen__DOT__imm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_imm_gen.varInsert(__Vfinal,"instruction", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_imm_gen__DOT__instruction), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_sim_soc__u_cpu__u_stage_id__u_imm_gen.varInsert(__Vfinal,"opcode", &(TOP.sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_imm_gen__DOT__opcode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
    }
}
