// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vsim_soc.h for the primary calling header

#ifndef VERILATED_VSIM_SOC___024ROOT_H_
#define VERILATED_VSIM_SOC___024ROOT_H_  // guard

#include "verilated.h"


class Vsim_soc__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vsim_soc___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ sim_soc__DOT__clk;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__clk;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__clk;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_csr__DOT__clk;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__clk;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__clk;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__clk;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__clk;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__clk;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__clk;
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        CData/*0:0*/ sim_soc__DOT__rst_n;
        CData/*0:0*/ sim_soc__DOT__cpu_rst;
        CData/*0:0*/ sim_soc__DOT__perip_wen;
        CData/*1:0*/ sim_soc__DOT__perip_mask;
        CData/*0:0*/ sim_soc__DOT__dram_sel;
        CData/*1:0*/ sim_soc__DOT__dram_offset;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__cpu_clk;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__cpu_rst;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__perip_wen;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__perip_mask;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__if_predicted;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__ifid_predicted;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__id_rs1_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__id_rs2_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__id_rd_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__id_alu_op;
        CData/*2:0*/ sim_soc__DOT__u_cpu__DOT__id_mem_funct3;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__id_alu_src;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__id_mem_read;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__id_mem_write;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__id_reg_write;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__id_wb_sel;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__id_branch;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__id_jal;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__id_jalr;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__id_auipc;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__id_ecall;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__id_mret;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__id_csr_op;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__idex_rs1_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__idex_rs2_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__idex_rd_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__idex_alu_op;
        CData/*2:0*/ sim_soc__DOT__u_cpu__DOT__idex_mem_funct3;
        CData/*2:0*/ sim_soc__DOT__u_cpu__DOT__idex_funct3;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__idex_alu_src;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__idex_mem_read;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__idex_mem_write;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__idex_reg_write;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__idex_wb_sel;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__idex_branch;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__idex_jal;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__idex_jalr;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__idex_auipc;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__idex_ecall;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__idex_mret;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__idex_csr_op;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__idex_predicted;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__ex_branch_taken;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__ex_trap_valid;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__ex_csr_wen;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__div_stall;
    };
    struct {
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__mul_stall;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__exmem_rd_addr;
        CData/*2:0*/ sim_soc__DOT__u_cpu__DOT__exmem_mem_funct3;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__exmem_mem_read;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__exmem_mem_write;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__exmem_reg_write;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__exmem_wb_sel;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__memwb_rd_addr;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__memwb_reg_write;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__memwb_wb_sel;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__hz_stall;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__forward_a;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__forward_b;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__ex_stall;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__pipeline_stall;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__direction_mismatch;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__target_mismatch;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__ex_redirect;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__flush;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__cpu_rst;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__stall;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__branch_taken;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__bht_update_valid;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__bht_update_taken;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__predicted;
        CData/*6:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__opcode;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__if_rd;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__if_rs1;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__if_is_jal;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__if_is_branch;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__bht_predict_taken;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__bht_wr_current;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__bht_wr_next;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__branch_predict_taken;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__if_is_jalr;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__if_rd_is_link;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__if_rs1_is_link;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__is_call;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__is_return;
        CData/*2:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__ras_ptr;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__ras_predict;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__if_predict;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__cpu_rst;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__stall;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__flush;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__if_predicted;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__ifid_predicted;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_csr__DOT__cpu_rst;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_csr__DOT__csr_wen;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_csr__DOT__trap_valid;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__cpu_rst;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__wb_reg_write;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__wb_rd_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__rs1_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__rs2_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__rd_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__alu_op;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__alu_src;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__mem_read;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__mem_write;
        CData/*2:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__mem_funct3;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__reg_write;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__wb_sel;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__branch;
    };
    struct {
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__jal;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__jalr;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__lui;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__auipc;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__ecall;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__mret;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__csr_op;
        CData/*6:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__opcode;
        CData/*2:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__f3;
        CData/*6:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__funct7;
        CData/*6:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_imm_gen__DOT__opcode;
        CData/*6:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__opcode;
        CData/*2:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__funct3;
        CData/*6:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__funct7;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__alu_op;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__alu_src;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__mem_read;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__mem_write;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__reg_write;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__wb_sel;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__branch;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__jal;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__jalr;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__lui;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__auipc;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ecall;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__mret;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__csr_op;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_hazard__DOT__idex_mem_read;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_hazard__DOT__idex_rd_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_hazard__DOT__ifid_rs1_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_hazard__DOT__ifid_rs2_addr;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_hazard__DOT__stall;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__cpu_rst;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__flush;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__hold;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_rs1_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_rs2_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_rd_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_alu_op;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_alu_src;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_mem_read;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_mem_write;
        CData/*2:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_mem_funct3;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_reg_write;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_wb_sel;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_branch;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_jal;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_jalr;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_auipc;
        CData/*2:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_funct3;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_ecall;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_mret;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_csr_op;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_predicted;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_rs1_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_rs2_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_rd_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_alu_op;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_alu_src;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_mem_read;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_mem_write;
        CData/*2:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_mem_funct3;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_reg_write;
    };
    struct {
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_wb_sel;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_branch;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_jal;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_jalr;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_auipc;
        CData/*2:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_funct3;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_ecall;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_mret;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_csr_op;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_predicted;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_fwd__DOT__idex_rs1_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_fwd__DOT__idex_rs2_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_fwd__DOT__exmem_rd_addr;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_fwd__DOT__exmem_reg_write;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_fwd__DOT__memwb_rd_addr;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_fwd__DOT__memwb_reg_write;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__u_fwd__DOT__forward_a;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__u_fwd__DOT__forward_b;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__cpu_rst;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_rs1_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_rs2_addr;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_alu_op;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_alu_src;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_branch;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_jal;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_jalr;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_auipc;
        CData/*2:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_funct3;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_ecall;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_mret;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_csr_op;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__forward_a;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__forward_b;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__branch_taken;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__trap_valid;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__csr_wen;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__div_stall;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__mul_stall;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__mul_a_sign;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__mul_b_sign;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__is_div_op;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__div_busy;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__div_done;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__div_start;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__div_op_signed;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__div_op_rem;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__is_mul_op;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__mul_valid;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__branch_cond;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__rst;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__start;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__op_signed;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__op_rem;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__busy;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__done;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__state;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__count;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__sign_q;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__sign_r;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__is_rem;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__can_sub;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__cpu_rst;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__flush;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__ex_rd_addr;
    };
    struct {
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__ex_mem_read;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__ex_mem_write;
        CData/*2:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__ex_mem_funct3;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__ex_reg_write;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__ex_wb_sel;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__exmem_rd_addr;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__exmem_mem_read;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__exmem_mem_write;
        CData/*2:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__exmem_mem_funct3;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__exmem_reg_write;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__exmem_wb_sel;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_mem__DOT__exmem_mem_read;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_mem__DOT__exmem_mem_write;
        CData/*2:0*/ sim_soc__DOT__u_cpu__DOT__u_mem__DOT__exmem_mem_funct3;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_mem__DOT__perip_wen;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__u_mem__DOT__perip_mask;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__cpu_rst;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__mem_rd_addr;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__mem_reg_write;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__mem_wb_sel;
        CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__memwb_rd_addr;
        CData/*0:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__memwb_reg_write;
        CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__memwb_wb_sel;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sim_soc__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sim_soc__DOT__u_cpu__DOT__u_if__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sim_soc__DOT__u_cpu__DOT__u_csr__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sim_soc__DOT__u_cpu__DOT__u_ex__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__clk__0;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ sim_soc__DOT__dram_word_addr;
        SData/*11:0*/ sim_soc__DOT__u_cpu__DOT__id_csr_addr;
        SData/*11:0*/ sim_soc__DOT__u_cpu__DOT__idex_csr_addr;
        SData/*11:0*/ sim_soc__DOT__u_cpu__DOT__ex_csr_waddr;
        SData/*8:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__bht_rd_idx;
        SData/*8:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__bht_wr_idx;
        SData/*11:0*/ sim_soc__DOT__u_cpu__DOT__u_csr__DOT__csr_raddr;
        SData/*11:0*/ sim_soc__DOT__u_cpu__DOT__u_csr__DOT__csr_waddr;
        SData/*11:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__csr_addr;
        SData/*11:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__funct12;
        SData/*11:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__funct12;
        SData/*11:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_csr_addr;
        SData/*11:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_csr_addr;
        SData/*11:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_csr_addr;
        SData/*11:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__csr_waddr;
        IData/*31:0*/ sim_soc__DOT__irom_addr;
        IData/*31:0*/ sim_soc__DOT__irom_data;
        IData/*31:0*/ sim_soc__DOT__perip_addr;
        IData/*31:0*/ sim_soc__DOT__perip_wdata;
        IData/*31:0*/ sim_soc__DOT__perip_rdata;
        IData/*31:0*/ sim_soc__DOT__dram_cur;
        IData/*31:0*/ sim_soc__DOT__dram_rdata;
        IData/*31:0*/ sim_soc__DOT__dram_wdata;
        IData/*31:0*/ sim_soc__DOT__ii;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__irom_addr;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__irom_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__perip_addr;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__perip_wdata;
    };
    struct {
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__perip_rdata;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__if_pc;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__if_pc_plus4;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__if_instruction;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__if_predicted_target;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__ifid_pc;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__ifid_pc_plus4;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__ifid_instruction;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__ifid_predicted_target;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__id_rs1_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__id_rs2_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__id_imm;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__id_csr_rdata;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__idex_pc;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__idex_pc_plus4;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__idex_rs1_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__idex_rs2_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__idex_imm;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__idex_csr_rdata;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__idex_predicted_target;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__ex_alu_result;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__ex_rs2_data_fwd;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__ex_branch_target;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__ex_trap_epc;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__ex_trap_mcause;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__ex_csr_wdata;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__exmem_pc_plus4;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__exmem_alu_result;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__exmem_rs2_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__exmem_fwd_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__mem_read_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__memwb_pc_plus4;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__memwb_alu_result;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__memwb_mem_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__memwb_write_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__wb_write_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__csr_mtvec;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__csr_mepc;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__id_csr_rdata_raw;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__ex_redirect_target;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__id_csr_rdata_fwd;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__branch_target;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__irom_word_addr;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__irom_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__bht_update_pc;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__pc_out;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__pc_plus4;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__instruction;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__predicted_target;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__jal_imm;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__jal_target;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__b_imm;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__branch_predict_target;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__bht_i;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__ras_top;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__if_predict_target;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__if_pc;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__if_pc_plus4;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__if_instruction;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__if_predicted_target;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__ifid_pc;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__ifid_pc_plus4;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__ifid_instruction;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_ifid__DOT__ifid_predicted_target;
    };
    struct {
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_csr__DOT__csr_rdata;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_csr__DOT__csr_wdata;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_csr__DOT__trap_epc;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_csr__DOT__trap_mcause;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_csr__DOT__mtvec;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_csr__DOT__mepc;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_csr__DOT__mcause;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_csr__DOT__mstatus;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_csr__DOT__mtval;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_csr__DOT__mscratch;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__instruction;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__wb_write_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__csr_rdata;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__rs1_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__rs2_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__imm;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__csr_rdata_out;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__i;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__rf_rs1;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__rf_rs2;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT____Vlvbound_h5af0bf87__0;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_imm_gen__DOT__instruction;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_imm_gen__DOT__imm;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_pc;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_pc_plus4;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_rs1_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_rs2_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_imm;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_csr_rdata;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__id_predicted_target;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_pc;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_pc_plus4;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_rs1_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_rs2_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_imm;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_csr_rdata;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_idex__DOT__idex_predicted_target;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_pc;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_pc_plus4;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_rs1_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_rs2_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_imm;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__idex_csr_rdata;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__csr_mtvec;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__csr_mepc;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__exmem_fwd_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__wb_write_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__alu_result;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__rs2_data_fwd;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__branch_target;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__trap_epc;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__trap_mcause;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__csr_wdata;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__fwd_a;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__fwd_b;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__alu_a;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__alu_b;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__div_result;
        VlWide<3>/*65:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__mul_result_r;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__alu_out;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__pc_branch;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__jalr_tgt;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__zimm;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__csr_wd;
    };
    struct {
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__dividend;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__divisor;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__result;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__quo;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__rem;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__div_reg;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__q_out;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__r_out;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__ex_pc_plus4;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__ex_alu_result;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__ex_rs2_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__exmem_pc_plus4;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__exmem_alu_result;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__exmem_rs2_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_exmem__DOT__exmem_fwd_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_mem__DOT__exmem_alu_result;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_mem__DOT__exmem_rs2_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_mem__DOT__perip_addr;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_mem__DOT__perip_wdata;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_mem__DOT__perip_rdata;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_mem__DOT__mem_read_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__mem_pc_plus4;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__mem_alu_result;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__mem_read_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__memwb_pc_plus4;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__memwb_alu_result;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__memwb_mem_data;
        IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_pipe_memwb__DOT__memwb_write_data;
        IData/*31:0*/ __VactIterCount;
        QData/*32:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__mul_op_a;
        QData/*32:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__mul_op_b;
        QData/*32:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__trial;
        VlUnpacked<IData/*31:0*/, 4096> sim_soc__DOT__imem;
        VlUnpacked<IData/*31:0*/, 65536> sim_soc__DOT__dmem;
        VlUnpacked<CData/*1:0*/, 512> sim_soc__DOT__u_cpu__DOT__u_if__DOT__bht;
        VlUnpacked<IData/*31:0*/, 8> sim_soc__DOT__u_cpu__DOT__u_if__DOT__ras;
        VlUnpacked<IData/*31:0*/, 31> sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__regfile;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<10> __VactTriggered;
    VlTriggerVec<10> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vsim_soc__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_ADD = 0U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_SUB = 1U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_SLL = 2U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_SLT = 3U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_SLTU = 4U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_XOR = 5U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_SRL = 6U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_SRA = 7U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_OR = 8U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_AND = 9U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_PASS_B = 0x0aU;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_MUL = 0x0bU;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_MULH = 0x0cU;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_MULHSU = 0x0dU;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_MULHU = 0x0eU;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_DIV = 0x0fU;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_DIVU = 0x10U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_REM = 0x11U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_stage_id__DOT__u_ctrl__DOT__ALU_REMU = 0x12U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_ADD = 0U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_SUB = 1U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_SLL = 2U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_SLT = 3U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_SLTU = 4U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_XOR = 5U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_SRL = 6U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_SRA = 7U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_OR = 8U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_AND = 9U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_PASS_B = 0x0aU;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_MUL = 0x0bU;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_MULH = 0x0cU;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_MULHSU = 0x0dU;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_MULHU = 0x0eU;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_DIV = 0x0fU;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_DIVU = 0x10U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_REM = 0x11U;
    static constexpr CData/*4:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__ALU_REMU = 0x12U;
    static constexpr CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__S_IDLE = 0U;
    static constexpr CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__S_CALC = 1U;
    static constexpr CData/*1:0*/ sim_soc__DOT__u_cpu__DOT__u_ex__DOT__u_div__DOT__S_DONE = 2U;
    static constexpr IData/*31:0*/ sim_soc__DOT__DRAM_BASE = 0x80100000U;
    static constexpr IData/*31:0*/ sim_soc__DOT__DRAM_END = 0x80140000U;
    static constexpr IData/*31:0*/ sim_soc__DOT__u_cpu__DOT__u_if__DOT__RESET_PC = 0x80000000U;

    // CONSTRUCTORS
    Vsim_soc___024root(Vsim_soc__Syms* symsp, const char* v__name);
    ~Vsim_soc___024root();
    VL_UNCOPYABLE(Vsim_soc___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
